### ISSUE TITLE
Seamless Checkout : IDENTITYACCESSTOKEN

### ISSUE THREAD

**Issue by prparamasivam** [paypal/merchant-sdk-dotnet#24]
Hi,
I am trying to integrate PayPal seamless checkout. I'm using .NET PayPalMerchantSDK for SetExpressCheckout API call.The documentation here https://developer.paypal.com/docs/integration/direct/identity/seamless-checkout/ states that I should be passing in an IDENTITYACCESSTOKEN parameter. However, this doesn't seem to be available in the sdk. Could you please guide on how to integrate?

**Comment by jziaja** [comment]
This request is being tracked internally at PayPal.  Currently, there are no plans to support seamless checkout in this SDK.
