### ISSUE TITLE
What should we use for ExpressCheckout

### ISSUE THREAD

**Issue by kfuller002** [paypal/merchant-sdk-dotnet#25]
If this package is being deprecated, what should we do about express checkout?  PayPal-NET-SDK
doesn't appear to support it, is express checkout also deprecated?

**Comment by jziaja** [comment]
Express Checkout is being replaced by [PayPal REST Payments](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/).  The PayPal-NET-SDK contains [samples](https://github.com/paypal/PayPal-NET-SDK/wiki/Samples) for how to interact with this API.
