### ISSUE TITLE
Unable to Create SSL/TLS Secure Connection

### ISSUE THREAD

**Issue by Lakhan3456** [paypal/merchant-sdk-dotnet#26]
Hi , I am trying to connect to paypal sandbox environment and I am using the below settings in my config file to connect.

configMap.Add("mode", "sandbox"); 
configMap.Add("account1.apiUsername", "jb-us-seller_api1.paypal.com");
 configMap.Add("account1.apiPassword", "WX4WTU3S8MY44S7F");
configMap.Add("account1.apiSignature","AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy");

But , while calling the below code :- 

SetExpressCheckoutResponseType response = null;

            try
            {
                response = service.SetExpressCheckout(expressCheckoutReq);
            }
            catch (System.Exception ex)
            {
                contextHttp.Response.Write(ex.Message);
                return;
            }
I am getting the error as below :- 

Invalid HTTP response The request was aborted: Could not create SSL/TLS secure channel.

Please help.

**Comment by pp-randy** [comment]
@Lakhan3456 Have you reviewed the .NET information here https://github.com/paypal/tls-update?  And are you using the most recent version of this SDK?

**Comment by mikerocha** [comment]
@pp-randy I'm experiencing this same issue as well, and it seems the information at the link provided suggests that the merchant SDK doesn't have TLS 1.2 support as of yet. Until it does, is it safe to assume our sandboxes will not work?

**Comment by pp-randy** [comment]
@mikerocha Thanks for keeping me honest here.  

Are you able update your core SDK dependency?  https://github.com/paypal/sdk-core-dotnet to the most recent version.

**Comment by mikerocha** [comment]
@pp-randy Thanks, your suggestion is spot on. I never attempted to update the package as the TLS update page suggested the Classic API SDK didn't support TLS 1.2. It's good to know this still works well.

**Comment by pp-randy** [comment]
@Lakhan3456 can you confirm updating the sdk core in your build is working for you? 

https://github.com/paypal/sdk-core-dotnet

**Comment by pp-randy** [comment]
Closing the issue out as updating the sdk core should resolve. Please let me know if that isn't the case.
