### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by kstubs** [paypal/merchant-sdk-dotnet#27]
I am experiencing this error in my C# web application.  It is actually breaking my entire website but only after I invoke the API.  Funny, the API works one time and then crashes the rest of my site.  So for example, I call the API to cancel a recurring billing plan and this works great.  Then if I do anything else on my site it crashes with the error: 

The request was aborted: Could not create SSL/TLS secure channel.

I find it strange that it works one time and then my entire site fails.  I'm testing locally.  I have made sure that I have latest version of mentioned code in support posts I have found.  I also have the following line in my class that initializes the PayPal service

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

The only difference I can note, after following along now with usage instructions from this page:  https://github.com/paypal/merchant-sdk-dotnet, is that I was setting up the configuration directly on the the config object reading credentials from app settings.  I've since moved these credentials to the PayPal configuration section and am running more tests.  I'll report back with my findings.

Karl..

**Comment by kstubs** [comment]
There is still an issue.  It seems it is related to a SUCCESS response from the request to cancel a recurring billing plan when calling the api like this:

 ```
var request = new PayPal.PayPalAPIInterfaceService.Model.ManageRecurringPaymentsProfileStatusRequestType();
            var wrapper = new PayPal.PayPalAPIInterfaceService.Model.ManageRecurringPaymentsProfileStatusReq();

            request.ManageRecurringPaymentsProfileStatusRequestDetails = new PayPal.PayPalAPIInterfaceService.Model.ManageRecurringPaymentsProfileStatusRequestDetailsType(ProfileID, PayPal.PayPalAPIInterfaceService.Model.StatusChangeActionType.CANCEL);
            wrapper.ManageRecurringPaymentsProfileStatusRequest = request;

            var result = _service.ManageRecurringPaymentsProfileStatus(wrapper);
```

My testing included calling the service several times with a previous cancelled subscriptions.  I then found an active one that needed to be canceled and I did and right after getting a SUCCESS response my entire site crashes.

**Comment by kstubs** [comment]
I'm closing this but first let me explain my findings.  I am making another API call to Amazon Dynamo DB and it complains when the securityProtocol is Tls12.  Not sure this is the best solution, but I set the security protocol just before each Api call.  The only thing that I am not sure of is concurrency in a website.  Is this a static setting or thread safe?  If thread safe than no issue, otherwise I am going to run into all sort of more issues!

**Comment by pp-randy** [comment]
@kstubs sorry for the late response.  I don't think that is a thread safe approach.  It seems you have probably read this though http://stackoverflow.com/questions/3791629/set-the-securityprotocol-ssl3-or-tls-on-the-net-httpwebrequest-per-request
