### ISSUE TITLE
overlap with button manager

### ISSUE THREAD

**Issue by tofutim** [paypal/merchant-sdk-dotnet#28]
I noticed there is some overlap here with the button manager sdk, e.g., BMCreateButtonReq in the service model. But there is no BMCreateButton. Is there another matching command I should be looking for?

**Comment by ppmtscory** [comment]
Please see my response via your other issue filed [here](https://github.com/paypal/buttonmanager-sdk-dotnet/issues/10).  I will close this one as a duplicate and we'll work through what you need on your other issue.
