### ISSUE TITLE
Is possible to  use recurrying with express check-out? 

### ISSUE THREAD

**Issue by MMrR0b0TT** [paypal/merchant-sdk-dotnet#30]

**Comment by pp-randy** [comment]
If you are working on a new integration I would point you to https://github.com/paypal/PayPal-NET-SDK and to look over Billing Agreements API https://developer.paypal.com/docs/api/payments.billing-agreements/.

However, yes this SDK does support Recurring Payments and you might find this Integration Guide helpful: https://devtools-paypal.com/guide/recurring_payment_ec/dotnet?interactive=ON&env=sandbox
