### ISSUE TITLE
PaymentItem Options are not being deserialized correctly

### ISSUE THREAD

**Issue by urasaber** [paypal/merchant-sdk-dotnet#35]
### General information

* SDK/Library version: 2.16.204
* Environment: Sandbox
* Language, language version, and OS: .net 4.5 windows 10

### Issue description
Response version:
`<Version xmlns="urn:ebay:apis:eBLBaseComponents">204.0</Version>`

Options in response:
`<Options xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:OptionType" value="50" name="Quantity"/>`
`<Options xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:OptionType" value="http://google.com" name="Some link"/>`

Changes from #31 broke it.

**Comment by pp-randy** [comment]
I will look into reproducing this issue.  If you can provide any more details about what is incorrect that would be helpful.  If you are always aware of a fix please feel free to submit a pull request.

**Comment by urasaber** [comment]
It's easy to reproduce. If payment item have any custom options, they will be included in response xml like:
`<Options xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:OptionType" value="50" name="Quantity"/>`
So, as you can see 'value' and 'name' are attributes, **not** nodes, but in sdk they are treated like nodes:
`ChildNode = xmlNode.SelectSingleNode("*[local-name() = 'name']");`

Should be:
`ChildNode = xmlNode.Attributes.GetNamedItem("name");`

I have a fix for it on my side, will do pull request when I'll have time.

**Comment by urasaber** [comment]
Submitted pull request #36

**Comment by pp-randy** [comment]
Thank you for the pull request.

**Comment by pp-randy** [comment]
We are following up further internally so if we do push updates for new API versions that we do not overwrite this change.

**Comment by urasaber** [comment]
Did I understand you correctly: you have an internal version of soap API which produces option values as nodes, not attributes. And because of this the SDK have this code for nodes?

**Comment by pp-randy** [comment]
I have merged your pull request, and anything internal can be resolved without holding up your fix.  Thank you for the pull request again.
